# Generated by Django 5.1.2 on 2024-10-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coftea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
