# Generated by Django 5.1.2 on 2024-11-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coftea', '0004_alter_ordertransaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='paymentMethod',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Gcash', 'G-Cash Wallet'), ('Paymaya', 'Maya Wallet')], default='Cash', max_length=20),
        ),
    ]
